### ISSUE TITLE
Microphones dont work when placed in survival

### ISSUE THREAD

**Issue by Rozbiynk** [squeeglii/SimpleVoiceChat-Wiretap#1] opened 2024-01-16 09:22 UTC
**Bug description**
If i pickup wiretap items when in survival, they just dont work. Everything is fine when head placed in creative

**Steps to reproduce the issue**
1. Go to survival
2. Get items
3. Place them
4. They dont work
5. Place them in creative
6. They work

**Expected behavior**
Wiretap working when crafted and placed in survival

**Log files**
Dont contain anything useful

**Versions**
- Minecraft version 1.20.1
- Fabric loader version 0.15.3
- Mod version 1.0.3

**Other mods**
Very many mods

**Comment by squeeglii** [comment] 2024-02-29 14:28
Could not reproduce on 1.0.3+1.20.1 - could you provide a mod list and logs?

Also, is the speaker block emitting note particles or not when turned on?

**Comment by squeeglii** [comment] 2024-03-01 14:17
Could you send your client-side logs as well please? I've tried to recreate it with the same version of SVC but still no luck :(

**Comment by Rozbiynk** [comment] 2024-03-01 15:52
i has same issue on another server

**Comment by Rozbiynk** [comment] 2024-03-01 19:16
hmm, issue happens only when you place your last block

**Comment by Rozbiynk** [comment] 2024-03-01 19:26
sorry, it was not so shadow extra. I think it patch for update suppression

**Comment by squeeglii** [comment] 2024-03-01 20:33
Alrighty then - if in any way it needs a tweak on wiretap's end - send another message and I'll reopen this issue.

Otherwise, marking as closed :)

**Closed by squeeglii** 2024-03-01 20:33 UTC
Labels: bug, cannot reproduce
